### ISSUE TITLE
Look into lazy asset loading

### ISSUE THREAD

**Issue by taylortom** [cgkineo/adapt_authoring#102]
1. It's been reported that lazy loading can break, meaning it's impossible to view assets (not heard anyone experiencing this recently).
1. If uploading a new file that doesn't fit in the first 'page' of assets, it isn't selected. Need to make sure it's visible onscreen (**maybe auto-applying a 'recent' sort will be an acceptable fix**)

**Comment by taylortom** [comment]
1. Depending on the size of your window, it's possible to break the lazy loading by making the browser big enough to contain all assets in the first page, thus meaning that the scroll event isn't fired.

**Comment by kineotesting** [comment]
Tom, if this concerns the asset manager, it seems to be working fine (single page of lots of assets has a scroll bar when maximised on a larger monitor)
