### ISSUE TITLE
System information doesn't show complete branch name

### ISSUE THREAD

**Issue by tomgreenfield** [cgkineo/adapt_authoring#149]
With branch name `issue/82`:

![issue](https://cloud.githubusercontent.com/assets/922987/20935902/945641de-bbd8-11e6-8c66-f687e994c63b.png)

**Comment by taylortom** [comment]
Fix this with #150

**Comment by taylortom** [comment]
This is very temperamental, and seems to break depending on the commit message too...

**Comment by taylortom** [comment]
Think this is now fixed
