### ISSUE TITLE
Plugin locations keys overwrite each other

### ISSUE THREAD

**Issue by taylortom** [cgkineo/adapt_authoring#169]
e.g. multiple themes could have the following:
```
pluginLocations: {
  course: {
    properties: {
      _appearance: {}
    }
  }
}
```
In the case of extensions, it's standard practice to use the extension name  here(e.g. `_assessment`).

This causes problems in contentmanager when schemas are built, as the code uses an `_.extend` which overwrites any existing values with the same (for the same location).

We need to be able to notify the user of this issue.

**Comment by kineotesting** [comment]
Not sure if this is something we can easily retest Tom - maybe ask a dev to double check
