### ISSUE TITLE
Multiple copy/paste bug

### ISSUE THREAD

**Issue by taylortom** [cgkineo/adapt_authoring#192]
If the user selects 'paste' multiple time before the page automatically reloads in response to the first click then multiple instances of the copied item is added. 

This allows a user to add multiple full-width components to the same block.

**Comment by taylortom** [comment]
Can't replicate this now.

**Comment by kineotesting** [comment]
Tom, is this referring to when you are with course structure and are copying/pasting a page? I was having trouble getting to paste to work at all - but I could well just be doing something incorrectly - lets take a look together
