### ISSUE TITLE
Error message on theming editor

### ISSUE THREAD

**Issue by marcnewport** [cgkineo/adapt_authoring#2]
Trying to choose a theme in the editor under course > theming and get the error:

> i is not a constructor

Seems the scemaType should be just 'theme' in frontend/src/core/editor/theming/views/editorThemingView.js on line 60

**Comment by taylortom** [comment]
The idea with the theming schemas is that each installed theme can have different attributes -- this is the reasoning behind specifying the schemaType as the theme name.
