### ISSUE TITLE
User disorientation

### ISSUE THREAD

**Issue by taylortom** [cgkineo/adapt_authoring#203]
When editing a course, on most pages of the tool there is no indication of which course the user is working on. I would say it's inevitable that someone hopping between (potentially similar) courses and editing may end up applying changes to a sister course of the one they intended to edit.

A label somewhere in the UI with the title of course would help prevent this.

**Comment by taylortom** [comment]
Clickable breadcrumbs have been added above the page title.

**Comment by kineotesting** [comment]
Tom - the breadcrumb trail tells me what I am doing, eg Dashboard  > Course structure  > Page structure but if I have multiple courses built in the tool, the breadcrumb trail doesn't tell me which one I am in - the trail doesn't include the course title
