### ISSUE TITLE
Revisit plugin architecture

### ISSUE THREAD

**Issue by taylortom** [cgkineo/adapt_authoring#31]
The ultimate goal here is to have just one folder for a server plugin to allow easy drag-and-drop. Things to think about:
- Localised strings using polyglot would ideally be located in plugin folder, not added to application.json
- How to deal with extending of core plugins (i.e. those in `/plugins/`). Think we should avoid any overriding, but should be able to add new plugins easily.
- Route handling

**Comment by oliverfoster** [comment]
+1 ```/plugins/```
