### ISSUE TITLE
Enable thumbnails in the asset library

### ISSUE THREAD

**Issue by taylortom** [cgkineo/adapt_authoring#38]

**Comment by taylortom** [comment]
Thumbnails confirmed working with ffmpeg, need to let client services know they need to install it.

**Comment by kineotesting** [comment]
There are thumbnails in the Asset details for each asset (right of screen in Asset manager, when asset clicked) - if that's what's meant here, fixed - if its supposed to display thumbnails in the main asset manager view, then not fixed
